package com.github.jesg.dither;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/*
 * #%L
 * dither
 * %%
 * Copyright (C) 2015 Jason Gowan
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/**
 * Generates test sets using IPOG or ATEG strategies.
 *
 * <p>
 * A parameter is represented as an {@code Object[]}. The parameter is represented by an array of
 * its values. For instance, an "color" parameter might be represented as {@code new Object[] {
 * "red", "green", "blue" }}.
 *
 * <p>
 * A constraint is represented as an {@code Integer[]} whose length is the number of parameters for
 * which tests are being generated. Each constraint is a (possibly partial) configuration of
 * parameter values to exclude from generated tests. For instance, with the parameters {@code {{"A",
 * "B", "C"}, {true, false}, {"red", "green", "blue"}}}, the constraint {@code {1, null, 2}} means
 * that tests of the form {@code {"B", *, "blue"}} should not be generated.
 *
 * <p>
 * A test is represented as {@code Object[]} in which the <i>i</i><sup>th</sup> element is the value
 * of the <i>i</i><sup>th</sup> parameter. For instance, with the parameters {@code {{"A", "B",
 * "C"}, {true, false}, {"red", "green", "blue"}}}, one possible test is {@code {"A", false,
 * "green"}}.
 *
 * <p>
 * For all methods, the coverage strength {@code t} between 2 and the number of parameters,
 * inclusive. Each parameter must have at least two values.
 */
public class Dither {

    /**
     * An empty set of constraints.
     */
    public static final Integer[][] EMPTY_CONSTRAINTS = new Integer[][]{};

    /**
     * An empty set of previously tested configurations.
     */
    public static final Object[][] EMPTY_PREVIOUSLY_TESTED = new Object[][]{};

    private Dither() {}

    /**
     * Returns tests generated by the IPOG strategy.
     *
     * @param t the coverage strength
     * @param params the parameters
     * @param constraints the constraints
     * @param previouslyTested the previously tested configurations
     * @return the tests
     *
     * @throws DitherError if inputs are not valid
     */
    public static Object[][] ipog(final int t, final Object[][] params, final Integer[][] constraints, final Object[][] previouslyTested)
            throws DitherError {
        validateInput(t, params);
        return new Ipog(params, t, constraints, previouslyTested).run();
    }

    /**
     * Returns tests generated by the IPOG strategy. No tests are considered as previously tested.
     *
     * @param t the coverage strength
     * @param params the parameters
     * @param constraints the constraints
     * @return the tests
     *
     * @throws DitherError if inputs are not valid
     */
    public static Object[][] ipog(final int t, final Object[][] params, final Integer[][] constraints)
            throws DitherError {
        validateInput(t, params);
        return new Ipog(params, t, constraints, EMPTY_PREVIOUSLY_TESTED).run();
    }

    /**
     * Returns tests generated by the IPOG strategy. No tests are considered as previously tested, and
     * no constraints are imposed.
     *
     * @param t the coverage strength
     * @param params the parameters
     * @return the tests
     *
     * @throws DitherError if inputs are not valid
     */
    public static Object[][] ipog(final int t, final Object[][] params)
            throws DitherError {
        validateInput(t, params);
        return new Ipog(params, t, EMPTY_CONSTRAINTS, EMPTY_PREVIOUSLY_TESTED).run();
    }

    /**
     * Returns tests generated by the IPOG strategy. No tests are considered as previously tested, no
     * constraints are imposed, and the coverage strength is {@code 2}.
     *
     * @param params the parameters
     * @return the tests
     *
     * @throws DitherError if inputs are not valid
     */
    public static Object[][] ipog(final Object[][] params)
            throws DitherError {
        validateInput(2, params);
        return new Ipog(params, 2, EMPTY_CONSTRAINTS, EMPTY_PREVIOUSLY_TESTED).run();
    }

    /**
     * Returns tests generated by the IPOG strategy.
     *
     * @param t the coverage strength
     * @param params the parameters; each element must be an {@code Object[]}
     * @param constraints the constraints; each element must be an {@code Integer[]}
     * @param previouslyTested the previously tested tests; each element must be an {@code Object[]}
     * @return the tests
     *
     * @throws DitherError if inputs are not valid
     */
    public static Object[][] ipog(final int t, final Object[] params, final Object[] constraints, final Object[] previouslyTested)
        throws DitherError {
        final Object[][] innerParams = new Object[params.length][];
        for(int i = 0; i < innerParams.length; i++) {
            innerParams[i] = (Object[]) params[i];
        }
        validateInput(t, innerParams);

        final Integer[][] innerConstraints = new Integer[constraints.length][];
        for(int i = 0; i < innerConstraints.length; i++) {
            innerConstraints[i] = (Integer[]) constraints[i];
        }

        final Object[][] innerPreviouslyTested = new Object[previouslyTested.length][];
        for(int i = 0; i < innerPreviouslyTested.length; i++) {
            innerPreviouslyTested[i] = (Object[]) previouslyTested[i];
        }

        return new Ipog(innerParams, t, innerConstraints, innerPreviouslyTested).run();
    }

    @Deprecated
    public static Object[][] ateg(final Object[][] params)
        throws DitherError {
        return aetg(params);
    }

    public static Object[][] aetg(final Object[][] params)
        throws DitherError {
        return aetg(2, params);
    }

    @Deprecated
    public static Object[][] ateg(final int t, final Object[][] params) {
        return aetg(t, params);
    }

    public static Object[][] aetg(final int t, final Object[][] params) {
        return aetg(t, null, params, EMPTY_CONSTRAINTS, EMPTY_PREVIOUSLY_TESTED);
    }

    @Deprecated
    public static Object[][] ateg(final int t, final Integer seed, final Object[][] params, final Integer[][] constraints, final Object[][] previouslyTested)
        throws DitherError {
        return aetg(t, seed, params, constraints, previouslyTested);
    }

    public static Object[][] aetg(final int t, final Integer seed, final Object[][] params, final Integer[][] constraints, final Object[][] previouslyTested)
        throws DitherError {
        validateInput(t, params);
        final ExecutorService executor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());
        Object[][] result = new Object[][]{};
        try {
            result = new AetgPairwise(t, seed, params, constraints, previouslyTested, executor).toArray();
        } finally {
            executor.shutdownNow();
        }
        return result;
    }

    @Deprecated
    public static Object[][] ateg(final int t, final Integer seed, final Object[] params, final Object[] constraints, final Object[] previouslyTested) {
        return aetg(t, seed, params, constraints, previouslyTested);
    }

    public static Object[][] aetg(final int t, final Integer seed, final Object[] params, final Object[] constraints, final Object[] previouslyTested) {
        final Object[][] innerParams = new Object[params.length][];
        for(int i = 0; i < innerParams.length; i++) {
            innerParams[i] = (Object[]) params[i];
        }
        validateInput(t, innerParams);

        final Integer[][] innerConstraints = new Integer[constraints.length][];
        for(int i = 0; i < innerConstraints.length; i++) {
            innerConstraints[i] = (Integer[]) constraints[i];
        }

        final Object[][] innerPreviouslyTested = new Object[previouslyTested.length][];
        for(int i = 0; i < innerPreviouslyTested.length; i++) {
            innerPreviouslyTested[i] = (Object[]) previouslyTested[i];
        }
		return aetg(t, seed, innerParams, innerConstraints, innerPreviouslyTested);
	}

    private static void validateInput(final int t, final Object[][] params) throws DitherError {
        if (t <= 1) {
            throw new DitherError("t must be >= 2");
        }

        if (t > params.length) {
            throw new DitherError("t must be <= params.length");
        }
        for (final Object[] param : params) {
            if (param.length < 2) {
                throw new DitherError("param length must be > 1");
            }
        }
    }
}
